{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.megamil.answerbot",
    "module": "flutter_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.1.aar",
          "url": "flutter_release-0.0.1.aar",
          "size": 6104467,
          "sha512": "335814aa0192174596c869cbb36e3858b97eb1b547da36b84b0767a1a55c4d1bee1921389a64a4b97c8137958c80c2155c5690b74154d50c0a12356e9b34fecc",
          "sha256": "1ecc70886fca4ffa9d498fc78ba6da8625b433f13d63133398302a84f10d8113",
          "sha1": "00ac0bdeb67d369867ac85aa63e642e737e4fc21",
          "md5": "d494b01368fec2e83d718bcaebf4f44c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b8d35810e91ab8fc39ba5e7a41bff6f697e8e3a8"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.1.aar",
          "url": "flutter_release-0.0.1.aar",
          "size": 6104467,
          "sha512": "335814aa0192174596c869cbb36e3858b97eb1b547da36b84b0767a1a55c4d1bee1921389a64a4b97c8137958c80c2155c5690b74154d50c0a12356e9b34fecc",
          "sha256": "1ecc70886fca4ffa9d498fc78ba6da8625b433f13d63133398302a84f10d8113",
          "sha1": "00ac0bdeb67d369867ac85aa63e642e737e4fc21",
          "md5": "d494b01368fec2e83d718bcaebf4f44c"
        }
      ]
    }
  ]
}
